#ifndef __CONFIG_H
#define __CONFIG_H

#define MAX_TIMER2_CCR 100
#define DEGREE90_SPEED 50
#define FINGER_STOP_SPEED MAX_TIMER2_CCR
#define FINGER_RESET_SPEED DEGREE90_SPEED
#define DEGREE90_SPEEDMAX_DECODER_NUM 200

#define DECODER_CYCLE_TIME_MS 1
#define DEAD_TIME_NUM 7
#define TIMER3_PERIOD_LOADING 10*DECODER_CYCLE_TIME_MS*DEAD_TIME_NUM
#define DEGREE90_MAX_RELOAD_VALUE TIMER3_PERIOD_LOADING/2
#define FINGER_RESET_MAX_RELOAD_VALUE TIMER3_PERIOD_LOADING/2
#define FINGER_RESET_K FINGER_RESET_A*FINGER_RESET_B
#define FINGER_RESET_A 2
#define FINGER_RESET_B 0*(DEAD_TIME_NUM-1)

#endif
